server:
  max-http-header-size: 65536
  servlet:
    port: 8080
    contextPath: /api
spring:

  application:
    name: technical-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: wecode

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect